const mongoose = require('mongoose');
const { Schema } = mongoose;

// ─────────────────────────────────────────────────────
// FEEDBACK SUB-DOCUMENT SCHEMA
// Embedded inside Application. Generated by the shared
// Feedback Generation Module for screening, interview,
// and exit flows.
// ─────────────────────────────────────────────────────

const feedbackSchema = new Schema(
  {
    stage: {
      type: String,
      enum: {
        values: ['screening', 'interview', 'exit'],
        message: '{VALUE} is not a valid feedback stage',
      },
      required: true,
    },
    feedbackText: {
      type: String,
      required: [true, 'Feedback text is required'],
    },
    strengths: {
      type: [String],
      default: [],
    },
    improvements: {
      type: [String],
      default: [],
    },
    score: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { _id: true }
);

// ─────────────────────────────────────────────────────
// APPLICATION MODEL
// Tracks a user's application to a specific role.
// Embeds feedback sub-documents (max ~3: screening, interview, exit).
// Status follows the pipeline: pending_screening → ... → offer_accepted/declined
// ─────────────────────────────────────────────────────

const applicationSchema = new Schema(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User reference is required'],
      index: true,
    },
    role: {
      type: Schema.Types.ObjectId,
      ref: 'Role',
      required: [true, 'Role reference is required'],
      index: true,
    },
    status: {
      type: String,
      enum: {
        values: [
          'pending_screening',
          'screening_passed',
          'screening_rejected',
          'interview_in_progress',
          'interview_passed',
          'interview_rejected',
          'offer_pending',
          'offer_accepted',
          'offer_declined',
        ],
        message: '{VALUE} is not a valid application status',
      },
      default: 'pending_screening',
    },
    cooldownUntil: {
      type: Date,
      default: null,
    },
    feedbacks: [feedbackSchema],
    screeningScore: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Virtuals ───────────────────────────────────
applicationSchema.virtual('isOnCooldown').get(function () {
  if (!this.cooldownUntil) return false;
  return new Date() < this.cooldownUntil;
});

applicationSchema.virtual('interview', {
  ref: 'Interview',
  localField: '_id',
  foreignField: 'application',
  justOne: true,
});

// ─── Indexes ────────────────────────────────────
// Prevent duplicate active applications to the same role
applicationSchema.index(
  { user: 1, role: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: {
        $nin: ['screening_rejected', 'interview_rejected', 'offer_declined'],
      },
    },
  }
);
applicationSchema.index({ status: 1 });
applicationSchema.index({ user: 1, status: 1 });

module.exports = mongoose.model('Application', applicationSchema);
