const employeeService = require('../src/services/employee.service');
const EmployeeRecord = require('../src/models/EmployeeRecord');
const Task = require('../src/models/Task');
const User = require('../src/models/User');
const Company = require('../src/models/Company');
const AIBot = require('../src/models/AIBot');
const aiService = require('../src/services/ai.service');

jest.mock('../src/models/EmployeeRecord');
jest.mock('../src/models/Task');
jest.mock('../src/models/User');
jest.mock('../src/models/Company');
jest.mock('../src/models/AIBot');
jest.mock('../src/services/ai.service');

describe('Sprint 4: AI-Bot Task Generator & Progressive Disciplinary Pipeline', () => {
  const userId = '507f1f77bcf86cd799439011';
  const employeeRecordId = '507f1f77bcf86cd799439055';
  const taskId = '507f1f77bcf86cd799439099';

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Dynamic Task Synthesis via Company AI Bot', () => {
    it('should synthesize daily task themed by deployed company bot', async () => {
      const mockBot = {
        _id: 'bot-123',
        name: 'OmniCoder-v4',
        systemPrompt: 'You are an autonomous senior technical lead.',
      };

      const mockEmployee = {
        _id: employeeRecordId,
        user: userId,
        employmentStatus: 'active',
        currentLevel: 'senior',
        role: { title: 'Lead Architect', domain: 'Cloud Infrastructure' },
        company: {
          name: 'Nexus Corp',
          domain: 'Cloud Infrastructure',
          pipeline: {
            dailyTaskBot: mockBot,
          },
        },
      };

      EmployeeRecord.findById.mockReturnValue({
        populate: jest.fn().mockResolvedValue(mockEmployee),
      });

      Task.create.mockImplementation(async (data) => ({
        _id: 'task-new-1',
        ...data,
      }));

      const task = await employeeService.generateDailyTask(userId);

      expect(task).toBeDefined();
      expect(task.title).toContain('[OmniCoder-v4] Lead Architect Daily Simulation');
      expect(task.description).toContain("Generated by autonomous company bot 'OmniCoder-v4'");
      expect(task.difficulty).toBe('hard');
      expect(task.expReward).toBe(100);
      expect(task.status).toBe('assigned');
      expect(Task.create).toHaveBeenCalledWith(
        expect.objectContaining({
          category: 'scenario',
          difficulty: 'hard',
          expReward: 100,
        })
      );
    });

    it('should fall back gracefully to template/AI generation if no bot is deployed', async () => {
      const mockEmployee = {
        _id: employeeRecordId,
        user: userId,
        employmentStatus: 'active',
        currentLevel: 'junior',
        role: { title: 'Junior Frontend Dev', domain: 'Frontend' },
        company: {
          name: 'Startup Inc',
          pipeline: { dailyTaskBot: null },
        },
      };

      EmployeeRecord.findById.mockReturnValue({
        populate: jest.fn().mockResolvedValue(mockEmployee),
      });

      Task.find.mockReturnValue({
        sort: jest.fn().mockReturnValue({
          limit: jest.fn().mockReturnValue({
            select: jest.fn().mockResolvedValue([]),
          }),
        }),
      });

      aiService.generateTask.mockResolvedValue({
        title: 'Fix React render loop in navbar',
        description: 'Optimize useEffect hooks to prevent cascading re-renders.',
        category: 'debugging',
      });

      Task.create.mockImplementation(async (data) => ({
        _id: 'task-fallback-1',
        ...data,
      }));

      const task = await employeeService.generateDailyTask(userId);

      expect(task).toBeDefined();
      expect(aiService.generateTask).toHaveBeenCalled();
      expect(task.title).toBe('Fix React render loop in navbar');
    });
  });

  describe('Progressive Disciplinary State Machine (3 Strikes)', () => {
    it('Strike 1: issues official warning and updates manager feedback history', async () => {
      const mockEmployee = {
        _id: employeeRecordId,
        user: userId,
        employmentStatus: 'active',
        currentLevel: 'mid',
        strikesCount: 0,
        disciplinaryStatus: 'good_standing',
        warnings: [],
        manager: {
          name: 'Sarah Chen',
          feedbackHistory: [],
        },
        save: jest.fn().mockResolvedValue(true),
      };

      EmployeeRecord.findOne.mockResolvedValue(mockEmployee);
      Task.findByIdAndUpdate.mockResolvedValue({ _id: taskId, status: 'failed' });

      const result = await employeeService.recordTaskFailure(
        userId,
        taskId,
        'Missed production hotfix sprint deadline'
      );

      expect(Task.findByIdAndUpdate).toHaveBeenCalledWith(taskId, { status: 'failed' });
      expect(mockEmployee.strikesCount).toBe(1);
      expect(mockEmployee.disciplinaryStatus).toBe('warning');
      expect(mockEmployee.warnings).toHaveLength(1);
      expect(mockEmployee.warnings[0].strikeNumber).toBe(1);
      expect(mockEmployee.warnings[0].reason).toBe('Missed production hotfix sprint deadline');
      expect(mockEmployee.manager.feedbackHistory).toHaveLength(1);
      expect(mockEmployee.manager.feedbackHistory[0].sentiment).toBe('warning');
      expect(mockEmployee.manager.feedbackHistory[0].note).toContain('Official Disciplinary Warning (Strike 1)');
      expect(mockEmployee.save).toHaveBeenCalled();

      expect(result.strikesCount).toBe(1);
      expect(result.disciplinaryStatus).toBe('warning');
      expect(result.demoted).toBe(false);
      expect(result.terminated).toBe(false);
      expect(result.message).toContain('Strike 1 recorded');
    });

    it('Strike 2: triggers level demotion (senior -> mid) and cuts salary by 15%', async () => {
      const mockEmployee = {
        _id: employeeRecordId,
        user: userId,
        employmentStatus: 'active',
        currentLevel: 'senior',
        strikesCount: 1,
        disciplinaryStatus: 'warning',
        warnings: [
          { strikeNumber: 1, reason: 'Previous failure', issuedAt: new Date() },
        ],
        salary: {
          currentSalary: 100000,
          salaryHistory: [{ amount: 100000, reason: 'Base compensation' }],
        },
        manager: {
          feedbackHistory: [],
        },
        save: jest.fn().mockResolvedValue(true),
      };

      EmployeeRecord.findOne.mockResolvedValue(mockEmployee);
      Task.findByIdAndUpdate.mockResolvedValue({ _id: taskId, status: 'failed' });

      const result = await employeeService.recordTaskFailure(
        userId,
        taskId,
        'Production regression in payment microservice'
      );

      expect(mockEmployee.strikesCount).toBe(2);
      expect(mockEmployee.disciplinaryStatus).toBe('pip_demotion');
      expect(mockEmployee.currentLevel).toBe('mid');
      expect(mockEmployee.salary.currentSalary).toBe(85000); // 15% cut
      expect(mockEmployee.salary.salaryHistory).toHaveLength(2);
      expect(mockEmployee.salary.salaryHistory[1].reason).toBe('Disciplinary Demotion: Strike 2 PIP Penalty');
      expect(mockEmployee.warnings).toHaveLength(2);
      expect(mockEmployee.save).toHaveBeenCalled();

      expect(result.strikesCount).toBe(2);
      expect(result.disciplinaryStatus).toBe('pip_demotion');
      expect(result.currentLevel).toBe('mid');
      expect(result.demoted).toBe(true);
      expect(result.terminated).toBe(false);
      expect(result.message).toContain('demoted and placed on PIP');
    });

    it('Strike 2: demotes mid level to junior', async () => {
      const mockEmployee = {
        _id: employeeRecordId,
        user: userId,
        employmentStatus: 'active',
        currentLevel: 'mid',
        strikesCount: 1,
        disciplinaryStatus: 'warning',
        warnings: [],
        salary: {
          currentSalary: 60000,
          salaryHistory: [],
        },
        manager: { feedbackHistory: [] },
        save: jest.fn().mockResolvedValue(true),
      };

      EmployeeRecord.findOne.mockResolvedValue(mockEmployee);

      const result = await employeeService.recordTaskFailure(userId, taskId, 'Failed sprint goal');

      expect(result.currentLevel).toBe('junior');
      expect(result.demoted).toBe(true);
      expect(mockEmployee.salary.currentSalary).toBe(51000); // 60000 * 0.85
    });

    it('Strike 3: terminates employee, stamps exitRecord, and reverts User to job_seeker', async () => {
      const mockEmployee = {
        _id: employeeRecordId,
        user: userId,
        employmentStatus: 'active',
        currentLevel: 'junior',
        strikesCount: 2,
        disciplinaryStatus: 'pip_demotion',
        warnings: [
          { strikeNumber: 1, reason: 'Warning 1' },
          { strikeNumber: 2, reason: 'Warning 2' },
        ],
        salary: { currentSalary: 51000 },
        manager: { feedbackHistory: [] },
        save: jest.fn().mockResolvedValue(true),
      };

      EmployeeRecord.findOne.mockResolvedValue(mockEmployee);
      User.findByIdAndUpdate.mockResolvedValue({ _id: userId, role: 'job_seeker' });

      const result = await employeeService.recordTaskFailure(
        userId,
        taskId,
        'Repeated critical delivery failure during PIP'
      );

      expect(mockEmployee.strikesCount).toBe(3);
      expect(mockEmployee.disciplinaryStatus).toBe('terminated');
      expect(mockEmployee.employmentStatus).toBe('terminated');
      expect(mockEmployee.exitRecord).toBeDefined();
      expect(mockEmployee.exitRecord.exitType).toBe('termination');
      expect(mockEmployee.exitRecord.reason).toContain('Involuntary dismissal: 3 disciplinary strikes accumulated.');
      expect(mockEmployee.exitRecord.feedbackText).toContain('Termination executed due to repeated failure');

      // Invariant: User role and status reverted to job_seeker
      expect(User.findByIdAndUpdate).toHaveBeenCalledWith(userId, {
        role: 'job_seeker',
        currentStatus: 'job_seeker',
      });

      expect(result.strikesCount).toBe(3);
      expect(result.disciplinaryStatus).toBe('terminated');
      expect(result.terminated).toBe(true);
      expect(result.message).toContain('Employment terminated. User reverted to Job Seeker.');
    });
  });

  describe('Controller endpoint failTask', () => {
    it('should process failure via controller and send ApiResponse', async () => {
      const employeeController = require('../src/controllers/employee.controller');

      const mockEmployee = {
        _id: employeeRecordId,
        user: userId,
        employmentStatus: 'active',
        currentLevel: 'junior',
        strikesCount: 0,
        disciplinaryStatus: 'good_standing',
        warnings: [],
        manager: { feedbackHistory: [] },
        save: jest.fn().mockResolvedValue(true),
      };

      EmployeeRecord.findOne.mockResolvedValue(mockEmployee);

      const req = {
        user: { _id: userId },
        body: {
          taskId,
          reason: 'Abandoned daily simulation task',
        },
      };

      const res = {
        status: jest.fn().mockReturnThis(),
        json: jest.fn(),
      };

      await employeeController.failTask(req, res);

      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({
          success: true,
          message: expect.stringContaining('Strike 1 recorded'),
          data: expect.objectContaining({
            strikesCount: 1,
            disciplinaryStatus: 'warning',
          }),
        })
      );
    });
  });
});
