const EmployeeRecord = require('../models/EmployeeRecord');
const Task = require('../models/Task');
const ExpLog = require('../models/ExpLog');
const User = require('../models/User');
const Role = require('../models/Role');
const Company = require('../models/Company');
const ApiError = require('../utils/ApiError');
const aiService = require('./ai.service');
const gamificationService = require('./gamification.service');
const {
  TASK_STATUS,
  TASK_DIFFICULTY,
  TASK_EXP_REWARD,
  TASK_BONUS,
  PERFORMANCE_STATUS,
  PERFORMANCE_CONFIG,
  PREVIOUS_LEVEL,
  EXP_SOURCE,
} = require('../utils/constants');

class EmployeeService {
  /**
   * Helper to resolve active employee record by record ID or user ID.
   */
  async _resolveActiveRecord(id) {
    let query = EmployeeRecord.findById(id);
    let record = query?.populate ? await query.populate('role company') : await query;
    if (!record) {
      query = EmployeeRecord.findOne({
        user: id,
        employmentStatus: { $in: ['active', 'notice_period'] },
      });
      record = query?.populate ? await query.populate('role company') : await query;
    }
    return record;
  }


  /**
   * Rolls a task difficulty based on the employee's current level.
   * - Junior: 60% easy, 30% medium, 10% hard
   * - Mid:    30% easy, 50% medium, 20% hard
   * - Senior: 10% easy, 40% medium, 50% hard
   */
  _pickDifficulty(level) {
    const roll = Math.random();
    if (level === 'senior') {
      if (roll < 0.10) return TASK_DIFFICULTY.EASY;
      if (roll < 0.50) return TASK_DIFFICULTY.MEDIUM;
      return TASK_DIFFICULTY.HARD;
    }
    if (level === 'mid') {
      if (roll < 0.30) return TASK_DIFFICULTY.EASY;
      if (roll < 0.80) return TASK_DIFFICULTY.MEDIUM;
      return TASK_DIFFICULTY.HARD;
    }
    // Default junior
    if (roll < 0.60) return TASK_DIFFICULTY.EASY;
    if (roll < 0.90) return TASK_DIFFICULTY.MEDIUM;
    return TASK_DIFFICULTY.HARD;
  }

  /**
   * Generates a contextual daily task using the founder's deployed company bot,
   * falling back smoothly to AI service or domain templates.
   * Accepts either employeeRecordId or userId.
   */
  async generateDailyTask(targetId) {
    const employee = await this._resolveActiveRecord(targetId);
    if (!employee || !['active', 'notice_period'].includes(employee.employmentStatus)) {
      throw ApiError.badRequest('No active employee record found to generate a task for');
    }

    let deployedBot = employee.company?.pipeline?.dailyTaskBot;
    if (deployedBot && (typeof deployedBot === 'string' || deployedBot._bsontype)) {
      try {
        const AIBot = require('../models/AIBot');
        const botDoc = await AIBot.findById(deployedBot);
        if (botDoc) deployedBot = botDoc;
      } catch (err) {
        // fallback to existing value
      }
    }
    const roleTitle = employee.role?.title || 'Software Engineer';
    const domain = employee.company?.domain || employee.role?.domain || 'Technology';

    // If company has deployed a dailyTaskBot, synthesize themed task
    if (deployedBot) {

      const difficulty =
        employee.currentLevel === 'senior' ? 'hard' : employee.currentLevel === 'mid' ? 'medium' : 'easy';
      const expReward =
        employee.currentLevel === 'senior' ? 100 : employee.currentLevel === 'mid' ? 60 : 40;

      const taskTitle = `[${deployedBot.name}] ${roleTitle} Daily Simulation`;
      const taskDescription = `Generated by autonomous company bot '${deployedBot.name}': Solve a realistic ${domain} scenario optimizing system uptime and user metrics.`;

      const task = await Task.create({
        employeeRecord: employee._id,
        title: taskTitle.slice(0, 200),
        description: taskDescription,
        category: 'scenario',
        difficulty,
        expReward,
        status: TASK_STATUS.ASSIGNED,
        assignedDate: new Date(),
        dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours
      });

      return task;
    }

    const difficulty = this._pickDifficulty(employee.currentLevel);

    const previousTasks = await Task.find({ employeeRecord: employee._id })
      .sort('-createdAt')
      .limit(5)
      .select('title difficulty');

    const generated = await aiService.generateTask({
      roleTitle: employee.role?.title || 'Software Engineer',
      level: employee.currentLevel || 'junior',
      domain: employee.role?.domain || 'Technology',
      difficulty,
      companyName: employee.company?.name || 'CorpVerse',
      previousTasks,
    });

    const expReward = TASK_EXP_REWARD[difficulty] || 25;

    const task = await Task.create({
      employeeRecord: employee._id,
      title: (generated.title || `Daily ${employee.currentLevel} Task`).slice(0, 200),
      description: generated.description || 'Complete the assigned daily objective.',
      status: TASK_STATUS.ASSIGNED,
      expReward,
      difficulty,
      category: generated.category || 'debugging',
    });

    return task;
  }

  async generateBotDailyTask(targetId) {
    return this.generateDailyTask(targetId);
  }

  /**
   * Records a task failure or missed deadline and applies progressive discipline
   */
  async recordTaskFailure(userId, taskId, reason = 'Failed to meet quality benchmark') {
    const employeeRecord = await EmployeeRecord.findOne({ user: userId, employmentStatus: 'active' });
    if (!employeeRecord) throw ApiError.notFound('Active employee record not found');

    // Mark task as failed
    if (taskId) {
      await Task.findByIdAndUpdate(taskId, { status: 'failed' });
    }

    employeeRecord.strikesCount = Math.min(3, (employeeRecord.strikesCount || 0) + 1);
    const strike = employeeRecord.strikesCount;

    let message = '';
    let demoted = false;
    let terminated = false;

    if (!employeeRecord.warnings) {
      employeeRecord.warnings = [];
    }
    if (!employeeRecord.manager) {
      employeeRecord.manager = {};
    }
    if (!employeeRecord.manager.feedbackHistory) {
      employeeRecord.manager.feedbackHistory = [];
    }

    if (strike === 1) {
      // STRIKE 1: Official Warning
      employeeRecord.disciplinaryStatus = 'warning';
      employeeRecord.warnings.push({
        reason,
        strikeNumber: 1,
        issuedAt: new Date(),
      });
      // Add warning feedback to manager history
      employeeRecord.manager.feedbackHistory.push({
        note: `Official Disciplinary Warning (Strike 1): ${reason}. Please consult team guidelines.`,
        sentiment: 'warning',
        date: new Date(),
      });
      message = 'Strike 1 recorded. Official disciplinary warning issued.';
    } else if (strike === 2) {
      // STRIKE 2: Demotion & PIP
      employeeRecord.disciplinaryStatus = 'pip_demotion';
      employeeRecord.warnings.push({
        reason,
        strikeNumber: 2,
        issuedAt: new Date(),
      });

      // Demote level if mid or senior
      if (employeeRecord.currentLevel === 'senior') {
        employeeRecord.currentLevel = 'mid';
        demoted = true;
      } else if (employeeRecord.currentLevel === 'mid') {
        employeeRecord.currentLevel = 'junior';
        demoted = true;
      }

      // Cut salary by 15%
      if (employeeRecord.salary) {
        employeeRecord.salary.currentSalary = Math.round(employeeRecord.salary.currentSalary * 0.85);
        if (!employeeRecord.salary.salaryHistory) {
          employeeRecord.salary.salaryHistory = [];
        }
        employeeRecord.salary.salaryHistory.push({
          amount: employeeRecord.salary.currentSalary,
          reason: 'Disciplinary Demotion: Strike 2 PIP Penalty',
          effectiveDate: new Date(),
        });
      }

      message = 'Strike 2 recorded. Employee demoted and placed on PIP!';
    } else if (strike >= 3) {
      // STRIKE 3: Termination (Fired)
      employeeRecord.disciplinaryStatus = 'terminated';
      employeeRecord.employmentStatus = 'terminated';
      employeeRecord.exitRecord = {
        exitType: 'termination',
        reason: `Involuntary dismissal: 3 disciplinary strikes accumulated. ${reason}`,
        feedbackText: 'Termination executed due to repeated failure to satisfy role benchmarks.',
        exitedAt: new Date(),
      };

      // Revert User to Job Seeker
      await User.findByIdAndUpdate(userId, {
        role: 'job_seeker',
        currentStatus: 'job_seeker',
      });

      terminated = true;
      message = 'Strike 3 recorded. Employment terminated. User reverted to Job Seeker.';
    }

    await employeeRecord.save();

    return {
      strikesCount: employeeRecord.strikesCount,
      disciplinaryStatus: employeeRecord.disciplinaryStatus,
      currentLevel: employeeRecord.currentLevel,
      demoted,
      terminated,
      message,
      exitRecord: employeeRecord.exitRecord,
    };

  }

  /**
   * Returns today's task for an employee if already generated.
   * "Today" is bounded by midnight start of today.
   */
  async getTodayTask(userId) {
    const employee = await this._resolveActiveRecord(userId);
    if (!employee || !['active', 'notice_period'].includes(employee.employmentStatus)) {
      throw ApiError.badRequest('No active employee record found');
    }

    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);

    const todayTask = await Task.findOne({
      employeeRecord: employee._id,
      createdAt: { $gte: todayStart },
    }).sort({ createdAt: -1 });

    return todayTask;
  }

  /**
   * Calculates the consecutive day streak of completed tasks for an employee.
   */
  async calculateStreak(employeeRecordId) {
    const tasks = await Task.find({
      employeeRecord: employeeRecordId,
      status: TASK_STATUS.COMPLETED,
      completedAt: { $ne: null },
    }).sort({ completedAt: -1 });

    if (!tasks.length) return 0;

    const completedDates = new Set(
      tasks.map((t) => new Date(t.completedAt).toISOString().split('T')[0])
    );

    let streak = 0;
    const current = new Date();
    current.setUTCDate(current.getUTCDate() - 1);

    while (true) {
      const dateStr = current.toISOString().split('T')[0];
      if (completedDates.has(dateStr)) {
        streak++;
        current.setUTCDate(current.getUTCDate() - 1);
      } else {
        break;
      }
    }

    const todayStr = new Date().toISOString().split('T')[0];
    if (completedDates.has(todayStr)) {
      streak += 1;
    }

    return streak;
  }

  /**
   * Completes a task, awards EXP with bonuses, creates ExpLog, checks promotions.
   */
  async completeTask(taskId, userId, submissionData = null) {
    const employee = await this._resolveActiveRecord(userId);
    if (!employee || !['active', 'notice_period'].includes(employee.employmentStatus)) {
      throw ApiError.badRequest('No active employee record found');
    }

    const task = await Task.findById(taskId);
    if (!task) {
      throw ApiError.notFound('Task not found');
    }

    if (task.employeeRecord.toString() !== employee._id.toString()) {
      throw ApiError.forbidden('You do not have permission to complete this task');
    }

    if (task.status === TASK_STATUS.COMPLETED) {
      throw ApiError.badRequest('Task has already been completed');
    }

    const baseExp = task.expReward || TASK_EXP_REWARD[task.difficulty] || 25;

    // Speed bonus: completed within first 2 hours
    const hoursElapsed = (Date.now() - new Date(task.createdAt).getTime()) / (1000 * 60 * 60);
    const earlyBonus = hoursElapsed <= TASK_BONUS.EARLY_COMPLETION_WINDOW_HOURS ? TASK_BONUS.EARLY_COMPLETION : 0;

    // Streak bonus: 3+ consecutive days
    const currentStreak = await this.calculateStreak(employee._id);
    // After today's completion, streak will be currentStreak + 1 (if today was not counted yet)
    const effectiveStreak = currentStreak >= TASK_BONUS.MIN_STREAK_DAYS ? currentStreak : currentStreak + 1;
    const streakBonus = effectiveStreak >= TASK_BONUS.MIN_STREAK_DAYS ? TASK_BONUS.STREAK : 0;

    const totalExp = baseExp + earlyBonus + streakBonus;

    // 5. Update Task
    task.status = TASK_STATUS.COMPLETED;
    task.completedAt = new Date();
    await task.save();

    // 6 & 7. Create ExpLog and update User expTotal
    const bonusLabels = [];
    if (streakBonus > 0) bonusLabels.push(`+${streakBonus} streak bonus`);
    if (earlyBonus > 0) bonusLabels.push(`+${earlyBonus} speed bonus`);
    const bonusText = bonusLabels.length ? ` (${bonusLabels.join(', ')})` : '';
    const reason = `Completed task "${task.title}" (+${baseExp} base${bonusText})`;

    await gamificationService.addExp(
      userId,
      totalExp,
      reason,
      EXP_SOURCE.TASK_COMPLETION,
      task._id,
      employee._id
    );

    // Update user streak on completion
    if (typeof gamificationService.updateStreak === 'function') {
      await gamificationService.updateStreak(userId);
    }

    // Award daily task CorpCoin bonus (+5 CorpCoins)
    if (typeof gamificationService.awardCoins === 'function') {
      await gamificationService.awardCoins(userId, 5, `Completed task "${task.title}"`);
    }

    // Check task count badges (tasks_10, tasks_50, tasks_100)
    if (typeof gamificationService.checkAndAwardBadges === 'function') {
      await gamificationService.checkAndAwardBadges(userId, 'task_completed');
    }

    // 8. Check for promotion
    const promotion = await gamificationService.checkPromotion(userId, employee._id);

    // 9. AI Team Manager dynamic feedback (FR-16)
    if (!employee.manager) {
      employee.manager = {
        name: 'Sarah Chen',
        avatarUrl: '/avatars/manager-1.png',
        title: 'Engineering Director',
        style: 'supportive',
        feedbackHistory: [],
      };
    }

    if (effectiveStreak >= 5) {
      const today = new Date().toISOString().split('T')[0];
      const hasRecentPraise = (employee.manager.feedbackHistory || []).some(
        (f) => f.sentiment === 'praise' && new Date(f.date).toISOString().split('T')[0] === today
      );
      if (!hasRecentPraise) {
        employee.manager.feedbackHistory.unshift({
          date: new Date(),
          note: "Outstanding momentum this week! You're operating well above peer baseline.",
          sentiment: 'praise',
        });
        await employee.save();
      }
    }

    return {
      task,
      expGained: totalExp,
      baseExp,
      bonuses: {
        streakBonus,
        earlyBonus,
      },
      streak: effectiveStreak,
      promotion,
    };
  }

  /**
   * Retrieves paginated tasks for an employee with status and difficulty filters.
   */
  async getMyTasks(userId, filters = {}) {
    const employee = await this._resolveActiveRecord(userId);
    if (!employee || !['active', 'notice_period'].includes(employee.employmentStatus)) {
      throw ApiError.badRequest('No active employee record found');
    }

    const { status, difficulty, fromDate, toDate, page = 1, limit = 10 } = filters;
    const query = { employeeRecord: employee._id };

    if (status && status !== 'all') {
      query.status = status;
    }
    if (difficulty && difficulty !== 'all') {
      query.difficulty = difficulty;
    }
    if (fromDate || toDate) {
      query.createdAt = {};
      if (fromDate) query.createdAt.$gte = new Date(fromDate);
      if (toDate) query.createdAt.$lte = new Date(toDate);
    }

    const skip = (parseInt(page) - 1) * parseInt(limit);
    const [tasks, total] = await Promise.all([
      Task.find(query).sort({ createdAt: -1 }).skip(skip).limit(parseInt(limit)),
      Task.countDocuments(query),
    ]);

    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    const todayTask = await Task.findOne({
      employeeRecord: employee._id,
      createdAt: { $gte: todayStart },
    }).sort({ createdAt: -1 });

    return {
      tasks,
      todayTask,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit),
      },
    };
  }

  /**
   * Retrieves paginated EXP history for the employee.
   */
  async getExpHistory(userId, { page = 1, limit = 10 } = {}) {
    const employee = await this._resolveActiveRecord(userId);
    const query = { user: userId };
    if (employee) {
      query.$or = [{ user: userId }, { employeeRecord: employee._id }];
    }

    const skip = (parseInt(page) - 1) * parseInt(limit);
    const [expLogs, total] = await Promise.all([
      ExpLog.find(query)
        .populate('taskId', 'title difficulty expReward category')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(parseInt(limit)),
      ExpLog.countDocuments(query),
    ]);

    return {
      expLogs,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit),
      },
    };
  }

  /**
   * Checks employee performance based on completed tasks over the past 7 days.
   * Can optionally apply consequences (EXP deductions, demotion, termination).
   */
  async checkPerformance(employeeRecordId, options = {}) {
    const { applyPenalties = false } = options;
    const record = await EmployeeRecord.findById(employeeRecordId);
    if (!record) {
      throw ApiError.notFound('Employee record not found');
    }

    const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const completedThisWeek = await Task.countDocuments({
      employeeRecord: record._id,
      status: TASK_STATUS.COMPLETED,
      completedAt: { $gte: weekAgo },
    });

    let status = PERFORMANCE_STATUS.GOOD;
    if (completedThisWeek < PERFORMANCE_CONFIG.CRITICAL_THRESHOLD_DAYS) {
      status = PERFORMANCE_STATUS.CRITICAL;
    } else if (completedThisWeek < PERFORMANCE_CONFIG.WARNING_THRESHOLD_DAYS) {
      status = PERFORMANCE_STATUS.WARNING;
    }

    let demoted = false;
    let terminated = false;
    let expPenalty = 0;
    let previousLevel = record.currentLevel;
    let newLevel = record.currentLevel;

    if (applyPenalties) {
      if (status === PERFORMANCE_STATUS.CRITICAL) {
        expPenalty = PERFORMANCE_CONFIG.EXP_PENALTY_CRITICAL;
        record.consecutiveCriticalWeeks = (record.consecutiveCriticalWeeks || 0) + 1;

        if (
          record.consecutiveCriticalWeeks >= PERFORMANCE_CONFIG.CONSECUTIVE_CRITICAL_TERMINATION &&
          record.currentLevel === 'junior'
        ) {
          // Fired / Terminated
          terminated = true;
          record.employmentStatus = 'terminated';
          record.exitRecord = {
            exitType: 'termination',
            reason: 'Performance termination: 3 consecutive critical weeks at junior level',
            exitedAt: new Date(),
          };

          await User.findByIdAndUpdate(record.user, {
            role: 'job_seeker',
            currentStatus: 'job_seeker',
          });

          const company = await Company.findById(record.company);
          if (company && company.employeeCount > 0) {
            company.employeeCount -= 1;
            await company.save();
          }
        } else if (record.consecutiveCriticalWeeks >= PERFORMANCE_CONFIG.CONSECUTIVE_CRITICAL_DEMOTION) {
          // Demote if higher than junior
          const demotedLevel = PREVIOUS_LEVEL[record.currentLevel];
          if (demotedLevel) {
            demoted = true;
            newLevel = demotedLevel;
            record.currentLevel = demotedLevel;
            record.consecutiveCriticalWeeks = 0; // reset counter on demotion
          }
        }
      } else if (status === PERFORMANCE_STATUS.WARNING) {
        expPenalty = PERFORMANCE_CONFIG.EXP_PENALTY_WARNING;
        record.consecutiveCriticalWeeks = 0;
      } else {
        record.consecutiveCriticalWeeks = 0;
      }

      if (expPenalty > 0) {
        await gamificationService.addExp(
          record.user,
          -expPenalty,
          `Performance review penalty: ${status} status (${completedThisWeek}/7 days completed)`,
          EXP_SOURCE.PENALTY,
          null,
          record._id
        );
      }

      record.performanceStatus = status;
      record.lastPerformanceCheckAt = new Date();
      await record.save();
    }

    return {
      status,
      completedThisWeek,
      consecutiveCriticalWeeks: record.consecutiveCriticalWeeks,
      demoted,
      terminated,
      previousLevel,
      newLevel,
      expPenalty,
      lastPerformanceCheckAt: record.lastPerformanceCheckAt,
    };
  }

  /**
   * Retrieves the current performance dashboard data for an employee.
   */
  async getPerformance(userId) {
    const employee = await this._resolveActiveRecord(userId);
    if (!employee || !['active', 'notice_period'].includes(employee.employmentStatus)) {
      throw ApiError.badRequest('No active employee record found');
    }

    const perf = await this.checkPerformance(employee._id, { applyPenalties: false });
    const streak = await this.calculateStreak(employee._id);

    let message = 'You are performing great! Keep up the daily momentum.';
    if (perf.status === PERFORMANCE_STATUS.WARNING) {
      message = 'Performance warning: You completed fewer than 3 tasks in the last 7 days. Complete daily tasks to avoid penalties.';
    } else if (perf.status === PERFORMANCE_STATUS.CRITICAL) {
      message = 'CRITICAL WARNING: 0 tasks completed this week. You are at risk of demotion or termination.';
    }

    return {
      ...perf,
      currentLevel: employee.currentLevel,
      streak,
      message,
    };
  }

  /**
   * Retrieves the employee's active record with populated company and role.
   */
  async getMyRecord(userId) {
    const employee = await EmployeeRecord.findOne({
      user: userId,
      employmentStatus: { $in: ['active', 'notice_period'] },
    }).populate('role company');
    if (!employee) {
      throw ApiError.notFound('No active employee record found');
    }
    return employee;
  }

  /**
   * AI Team Manager: Retrieves designated team manager profile and feedback history (FR-16).
   */
  async getManagerProfile(userId) {
    const employee = await this._resolveActiveRecord(userId);
    if (!employee) {
      throw ApiError.notFound('No active employee record found');
    }

    if (!employee.manager) {
      employee.manager = {
        name: 'Sarah Chen',
        avatarUrl: '/avatars/manager-1.png',
        title: 'Engineering Director',
        style: 'supportive',
        feedbackHistory: [
          {
            date: new Date(),
            note: 'Welcome to the team! Thrilled to have you on board. Keep up steady sprint execution and check in with me whenever needed.',
            sentiment: 'neutral',
          },
        ],
      };
      await employee.save();
    }

    return employee.manager;
  }

  /**
   * AI Team Manager: Requests an immediate 1-on-1 performance & advisory check-in (FR-16).
   */
  async request1On1Feedback(userId) {
    const employee = await this._resolveActiveRecord(userId);
    if (!employee) {
      throw ApiError.notFound('No active employee record found');
    }

    const streak = await this.calculateStreak(employee._id);
    const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const completedThisWeek = await Task.countDocuments({
      employeeRecord: employee._id,
      status: TASK_STATUS.COMPLETED,
      completedAt: { $gte: weekAgo },
    });

    let note = '';
    let sentiment = 'neutral';

    if (completedThisWeek >= 4 || streak >= 5) {
      note = `Exceptional momentum this week! You have completed ${completedThisWeek} tasks with a ${streak}-day streak. You're operating well above peer baseline.`;
      sentiment = 'praise';
    } else if (completedThisWeek === 0) {
      note = "I noticed you haven't checked in on your sprint tasks for several days. Let me know if you need unblocking or have system hurdles.";
      sentiment = 'warning';
    } else {
      note = `Steady sprint execution with ${completedThisWeek} task(s) logged recently. Keep focusing on quality submissions and daily momentum to accelerate your promotion readiness.`;
      sentiment = 'neutral';
    }

    const feedbackEntry = {
      date: new Date(),
      note,
      sentiment,
    };

    if (!employee.manager) {
      employee.manager = {
        name: 'Sarah Chen',
        avatarUrl: '/avatars/manager-1.png',
        title: 'Engineering Director',
        style: 'supportive',
        feedbackHistory: [],
      };
    }

    employee.manager.feedbackHistory.unshift(feedbackEntry);
    await employee.save();

    return {
      manager: employee.manager,
      latestFeedback: feedbackEntry,
      message: note,
    };
  }

  /**
   * Performance Reviews & Merit Raises (FR-17 & FR-18).
   * Evaluates task count, difficulty, and streak to calculate Performance Score (0-100).
   * Score >= 85: Grants 10% Merit Salary Raise & 50 CorpCoins.
   * Score >= 70: Awards 50 EXP bonus.
   * Score < 50: Warning status (light PIP watch).
   */
  async requestPerformanceReview(userId) {
    const employee = await this._resolveActiveRecord(userId);
    if (!employee) {
      throw ApiError.notFound('No active employee record found');
    }

    const completedCount = await Task.countDocuments({
      employeeRecord: employee._id,
      status: TASK_STATUS.COMPLETED,
    });

    if (completedCount < 5) {
      throw ApiError.badRequest(
        `Minimum 5 completed tasks required to request a performance review. Current: ${completedCount}/5 completed.`
      );
    }

    const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const completedThisWeek = await Task.countDocuments({
      employeeRecord: employee._id,
      status: TASK_STATUS.COMPLETED,
      completedAt: { $gte: weekAgo },
    });

    const streak = await this.calculateStreak(employee._id);

    const completedTasks = await Task.find({
      employeeRecord: employee._id,
      status: TASK_STATUS.COMPLETED,
    }).select('difficulty');

    let diffWeightSum = 0;
    completedTasks.forEach((t) => {
      if (t.difficulty === TASK_DIFFICULTY.HARD) diffWeightSum += 3;
      else if (t.difficulty === TASK_DIFFICULTY.MEDIUM) diffWeightSum += 2;
      else diffWeightSum += 1;
    });
    const avgDiff = completedTasks.length ? diffWeightSum / completedTasks.length : 2;
    const avgDiffLabel = avgDiff >= 2.5 ? 'hard' : avgDiff >= 1.7 ? 'medium' : 'easy';

    // Performance Score Formula (0-100):
    // Baseline for qualified employee meeting threshold (35 pts)
    const basePts = 35;
    // Consistency (up to 30 pts)
    const consistencyPts = Math.min(30, Math.round((completedThisWeek / 5) * 30));
    // Volume (up to 20 pts)
    const volumePts = Math.min(20, Math.round((completedCount / 10) * 20));
    // Difficulty (up to 10 pts)
    const difficultyPts = Math.round(((avgDiff - 1) / 2) * 10);
    // Streak (up to 10 pts)
    const streakPts = Math.min(10, streak * 2);

    const rawScore = basePts + consistencyPts + volumePts + difficultyPts + streakPts;
    const score = Math.max(30, Math.min(100, rawScore));

    const currentSalary = employee.salary?.currentSalary || 85000;
    let verdict = 'satisfactory';
    let salaryChange = 0;
    let expAwarded = 0;
    let summary = '';

    if (score >= 85) {
      verdict = 'merit_raise';
      salaryChange = Math.round(currentSalary * 0.10); // +10% Merit Raise
      const newSalary = currentSalary + salaryChange;

      if (!employee.salary) {
        employee.salary = { currentSalary, salaryHistory: [] };
      }

      employee.salary.currentSalary = newSalary;
      employee.salary.salaryHistory.push({
        effectiveDate: new Date(),
        amount: newSalary,
        reason: `Merit Salary Raise (+10%) from Outstanding Performance Review (Score: ${score}/100)`,
      });

      // Bonus CorpCoins (+50)
      if (typeof gamificationService.awardCoins === 'function') {
        await gamificationService.awardCoins(userId, 50, `Merit Raise milestone bonus (Score: ${score})`);
      }

      summary = `Executive review scored at ${score}/100 (Exemplary). Awarded a 10% merit salary increase (+$${salaryChange.toLocaleString()}/yr) and 50 CorpCoins bonus.`;

      if (employee.manager) {
        employee.manager.feedbackHistory.unshift({
          date: new Date(),
          note: `Phenomenal performance review (${score}/100)! In recognition of your exemplary execution, you have been awarded a 10% merit raise to $${newSalary.toLocaleString()}.`,
          sentiment: 'praise',
        });
      }
    } else if (score >= 50) {
      verdict = 'satisfactory';
      if (score >= 70) {
        expAwarded = 50;
        await gamificationService.awardExp(
          userId,
          expAwarded,
          EXP_SOURCE.PERFORMANCE_REVIEW || 'performance_review',
          { reason: `Performance review score ${score}/100` }
        );
        summary = `Review evaluated as satisfactory (${score}/100). Solid sprint execution. Awarded +50 EXP merit milestone bonus.`;
      } else {
        summary = `Review evaluated as satisfactory (${score}/100). Consistent milestone delivery.`;
      }

      if (employee.manager) {
        employee.manager.feedbackHistory.unshift({
          date: new Date(),
          note: `Solid sprint review (${score}/100)! Keep building daily consistency toward your next merit raise!`,
          sentiment: 'praise',
        });
      }
    } else {
      verdict = 'needs_improvement';
      employee.performanceStatus = 'warning';
      summary = `Review identified areas requiring velocity improvement (${score}/100). Placed on constructive coaching watch.`;

      if (employee.manager) {
        employee.manager.feedbackHistory.unshift({
          date: new Date(),
          note: `Performance review indicated areas for improvement (${score}/100). Let's connect on sprint blockers and get back on track.`,
          sentiment: 'warning',
        });
      }
    }

    employee.lastReviewDate = new Date();
    employee.nextReviewEligibleDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);

    if (!employee.reviewHistory) employee.reviewHistory = [];
    employee.reviewHistory.unshift({
      reviewDate: new Date(),
      score,
      verdict,
      salaryChange,
      expAwarded,
      summary,
      metrics: {
        completedTasksCount: completedCount,
        averageDifficulty: avgDiffLabel,
        streak,
      },
    });

    await employee.save();

    return {
      score,
      verdict,
      salaryChange,
      newSalary: employee.salary?.currentSalary || currentSalary,
      expAwarded,
      summary,
      nextReviewEligibleDate: employee.nextReviewEligibleDate,
      metrics: {
        completedTasksCount: completedCount,
        completedThisWeek,
        averageDifficulty: avgDiffLabel,
        streak,
      },
    };
  }

  /**
   * Resignation Notice Period: Initiates a 2-task transition notice period (FR-20).
   */
  async initiateNoticePeriod(userId, reason = 'Voluntary transition') {
    let query = EmployeeRecord.findOne({
      user: userId,
      employmentStatus: { $in: ['active', 'notice_period'] },
    });
    if (query && typeof query.populate === 'function') {
      query = query.populate('company role');
    }
    const employee = await query;

    if (!employee) {
      throw ApiError.badRequest('No active employee record found to resign from');
    }

    if (employee.employmentStatus === 'notice_period') {
      return {
        success: true,
        message: 'Notice period is already in progress.',
        noticePeriod: employee.noticePeriod,
      };
    }

    employee.employmentStatus = 'notice_period';
    employee.noticePeriod = {
      initiatedAt: new Date(),
      targetCompletionDate: new Date(Date.now() + 48 * 60 * 60 * 1000),
      reason,
      noticeTasksRemaining: 2,
      handoverTasks: [
        {
          title: 'Architecture & Codebase Handover Documentation',
          description: 'Document active architecture modules, commit final pull requests, and archive technical debt logs.',
          isCompleted: false,
          completedAt: null,
        },
        {
          title: 'Knowledge Transfer & Team Transition Briefing',
          description: 'Conduct architecture transition sync with Sarah Chen and the engineering pod.',
          isCompleted: false,
          completedAt: null,
        },
      ],
      referenceLetter: null,
    };

    if (employee.manager) {
      employee.manager.feedbackHistory.unshift({
        date: new Date(),
        note: 'Resignation notice acknowledged. Transition handover checklist generated.',
        sentiment: 'neutral',
      });
    }

    await employee.save();

    return {
      success: true,
      message: 'Notice period initiated. Please complete 2 transition tasks.',
      noticePeriod: employee.noticePeriod,
    };
  }

  /**
   * Resignation Notice Period: Completes a transition handover task (FR-20).
   */
  async completeNoticeTask(userId, taskIndex = 0) {
    let query = EmployeeRecord.findOne({
      user: userId,
      employmentStatus: 'notice_period',
    });
    if (query && typeof query.populate === 'function') {
      query = query.populate('company role');
    }
    const employee = await query;

    if (!employee) {
      throw ApiError.badRequest('Employee is not currently in a notice period');
    }

    const index = parseInt(taskIndex, 10);
    const tasks = employee.noticePeriod?.handoverTasks || [];
    if (isNaN(index) || index < 0 || index >= tasks.length) {
      throw ApiError.badRequest('Invalid handover task index');
    }

    const task = tasks[index];
    if (task.isCompleted) {
      return {
        success: true,
        finalized: false,
        noticePeriod: employee.noticePeriod,
        message: 'This handover task is already completed.',
      };
    }

    task.isCompleted = true;
    task.completedAt = new Date();

    const remaining = tasks.filter((t) => !t.isCompleted).length;
    employee.noticePeriod.noticeTasksRemaining = remaining;

    if (remaining === 0) {
      return this.finalizeNoticePeriod(employee, userId);
    }

    await employee.save();

    return {
      success: true,
      finalized: false,
      noticePeriod: employee.noticePeriod,
      message: `Handover task completed! ${remaining} task(s) remaining.`,
    };
  }

  /**
   * Finalizes resignation departure, generates reference letter and alumni credentials (FR-20).
   */
  async finalizeNoticePeriod(employee, userId) {
    employee.employmentStatus = 'resigned';
    employee.exitRecord = {
      exitType: 'resignation',
      reason: employee.noticePeriod?.reason || 'Completed notice period and handover',
      feedbackText: 'Successfully completed full notice period and handover tasks with distinction. Recommended for future alumni network rehire.',
      exitedAt: new Date(),
    };

    const user = await User.findById(userId);
    const company = await Company.findById(employee.company);
    const role = await Role.findById(employee.role);

    const companyName = company?.name || 'CorpVerse Enterprise';
    const roleTitle = role?.title || 'Engineer';
    const tenure = `${new Date(employee.hiredAt).toLocaleDateString()} – ${new Date().toLocaleDateString()}`;

    employee.noticePeriod.referenceLetter = {
      companyName,
      roleTitle,
      employeeName: user?.name || 'Employee',
      tenure,
      rating: 'Exemplary Handover & Professionalism',
      text: `This letter confirms that ${user?.name || 'The employee'} has concluded their tenure as a ${roleTitle} at ${companyName}. Throughout their term and structured notice period, they completed all handover documentation, technical briefings, and sprint knowledge transfers with distinction. We recommend them highly for future opportunities.`,
      issuedAt: new Date(),
    };

    await employee.save();

    // Revert user to job_seeker
    await User.findByIdAndUpdate(userId, {
      role: 'job_seeker',
      currentStatus: 'job_seeker',
    });

    if (company && company.employeeCount > 0) {
      company.employeeCount -= 1;
      await company.save();
    }

    return {
      success: true,
      finalized: true,
      message: 'Notice period successfully completed. You have transitioned to Job Seeker status.',
      exitRecord: employee.exitRecord,
      referenceLetter: employee.noticePeriod.referenceLetter,
    };
  }

  /**
   * Retrieves exit certificate & reference letter for an employee (FR-20).
   */
  async getExitCertificate(userId) {
    let query = EmployeeRecord.findOne({
      user: userId,
      employmentStatus: { $in: ['notice_period', 'resigned'] },
    });
    if (query && typeof query.populate === 'function') {
      query = query.populate('company role');
    }
    const employee = await query;

    if (!employee || !employee.noticePeriod?.referenceLetter) {
      throw ApiError.notFound('No alumni certificate or reference letter found');
    }

    return employee.noticePeriod.referenceLetter;
  }

  /**
   * Resignation: Directly marks as resigned, resets user role/status and decrements company employeeCount.
   */
  async resign(userId, reason = 'Player resigned') {
    const employee = await EmployeeRecord.findOne({
      user: userId,
      employmentStatus: { $in: ['active', 'notice_period'] },
    });
    if (!employee) {
      throw ApiError.badRequest('No active employee record found to resign from');
    }

    employee.employmentStatus = 'resigned';
    employee.exitRecord = {
      exitType: 'resignation',
      reason,
      exitedAt: new Date(),
    };
    await employee.save();

    await User.findByIdAndUpdate(userId, {
      role: 'job_seeker',
      currentStatus: 'job_seeker',
    });

    const company = await Company.findById(employee.company);
    if (company && company.employeeCount > 0) {
      company.employeeCount -= 1;
      await company.save();
    }

    return {
      success: true,
      message: 'Resignation accepted. You have returned to job seeker status.',
      exitRecord: employee.exitRecord,
    };
  }
}

module.exports = new EmployeeService();
